import React,{useEffect,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {Link,Plus,Trash2,LogOut,Copy,ExternalLink,LayoutDashboard,Settings,BarChart3,UserRound,ArrowUpRight} from 'lucide-react';
import './styles.css';

const API='/api';
type User={id:string;username:string;email:string;displayName:string;bio?:string;avatar?:string};
type Item={id:string;title:string;url:string;description?:string;clicks:number};
type PublicProfile={username:string;displayName:string;bio?:string;avatar?:string;links:Item[]};

function PublicPage({username}:{username:string}){
 const [profile,setProfile]=useState<PublicProfile|null>(null); const [error,setError]=useState(false);
 useEffect(()=>{fetch(`${API}/public/${encodeURIComponent(username)}`).then(r=>r.ok?r.json():Promise.reject()).then(setProfile).catch(()=>setError(true))},[username]);
 if(error)return <main className="public"><section className="public-card"><h1>Perfil não encontrado</h1><p>Esse usuário não existe ou não está disponível.</p></section></main>;
 if(!profile)return <main className="public"><section className="public-card"><p>Carregando...</p></section></main>;
 return <main className="public"><section className="public-card"><div className="public-avatar">{profile.avatar?<img src={profile.avatar} alt=""/>:profile.displayName?.[0]?.toUpperCase()}</div><h1>{profile.displayName}</h1><p className="handle">@{profile.username}</p>{profile.bio&&<p className="bio">{profile.bio}</p>}<div className="public-links">{profile.links.map(l=><a className="public-link" key={l.id} href={`${API}/go/${l.id}`}><span><b>{l.title}</b>{l.description&&<small>{l.description}</small>}</span><ArrowUpRight size={19}/></a>)}</div><footer>LinkStash</footer></section></main>;
}

function App(){
 const path=location.pathname.replace(/\/+$/,''); if(path.startsWith('/u/')) return <PublicPage username={decodeURIComponent(path.slice(3))}/>;
 const [token,setToken]=useState(localStorage.getItem('token')||''); const [user,setUser]=useState<User|null>(null); const [links,setLinks]=useState<Item[]>([]); const [auth,setAuth]=useState<'login'|'register'>('login'); const [page,setPage]=useState('dashboard'); const [form,setForm]=useState({email:'',password:'',username:'',displayName:''}); const [newLink,setNewLink]=useState({title:'',url:'',description:''}); const [saving,setSaving]=useState(false);
 const headers=()=>({'Content-Type':'application/json',Authorization:`Bearer ${token}`});
 const load=async()=>{if(!token)return;const u=await fetch(`${API}/me`,{headers:headers()});if(!u.ok){localStorage.removeItem('token');setToken('');setUser(null);return}setUser(await u.json());const l=await fetch(`${API}/links`,{headers:headers()});if(l.ok)setLinks(await l.json())};
 useEffect(()=>{load()},[token]);
 const logout=()=>{localStorage.removeItem('token');setToken('');setUser(null)};
 const submitAuth=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);try{const endpoint=auth==='login'?'/auth/login':'/auth/register';const body=auth==='login'?{email:form.email,password:form.password}:form;const r=await fetch(API+endpoint,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json();if(!r.ok)return alert(d.error||'Erro');localStorage.setItem('token',d.token);setToken(d.token);}finally{setSaving(false)}};
 const add=async(e:React.FormEvent)=>{e.preventDefault();const r=await fetch(`${API}/links`,{method:'POST',headers:headers(),body:JSON.stringify(newLink)});if(r.ok){setLinks([...links,await r.json()]);setNewLink({title:'',url:'',description:''})}else{const d=await r.json();alert(d.error||'Erro ao salvar')}};
 const del=async(id:string)=>{if(!confirm('Excluir este link?'))return;const r=await fetch(`${API}/links/${id}`,{method:'DELETE',headers:headers()});if(r.ok)setLinks(links.filter(x=>x.id!==id))};
 const publicUrl=`${location.origin}/u/${user?.username||''}`;
 if(!token||!user)return <main className="auth"><section className="auth-card"><div className="brand"><Link/><b>LinkStash</b></div><p>Seu hub pessoal de links.</p><div className="tabs"><button className={auth==='login'?'active':''} onClick={()=>setAuth('login')}>Entrar</button><button className={auth==='register'?'active':''} onClick={()=>setAuth('register')}>Criar conta</button></div><form onSubmit={submitAuth}>{auth==='register'&&<><input placeholder="Usuário (3-50: letras, números, _)" required value={form.username} onChange={e=>setForm({...form,username:e.target.value})}/><input placeholder="Nome" required value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/></>}<input type="email" placeholder="Email" required value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input type="password" placeholder="Senha (mín. 6)" required value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><button className="primary" disabled={saving}>{saving?'Aguarde...':auth==='login'?'Entrar':'Criar conta'}</button></form></section></main>;
 const nav=[['dashboard',LayoutDashboard,'Dashboard'],['links',Link,'Meus Links'],['analytics',BarChart3,'Análises'],['profile',UserRound,'Perfil'],['settings',Settings,'Configurações']] as const;
 return <div className="app"><aside><div className="brand"><Link/><b>LinkStash</b></div>{nav.map(([id,I,label])=><button className={page===id?'nav active':'nav'} onClick={()=>setPage(id)} key={id}>{React.createElement(I,{size:18})}{label}</button>)}<button className="logout" onClick={logout}><LogOut size={18}/>Sair</button></aside><section className="content"><header><div><small>LinkStash</small><h1>{page==='dashboard'?'Dashboard':page==='links'?'Meus Links':page==='analytics'?'Análises':page==='profile'?'Meu Perfil':'Configurações'}</h1></div><div className="user"><span>{user.displayName}</span><div className="avatar">{user.displayName?.[0]?.toUpperCase()}</div></div></header>
 {page==='dashboard'&&<Dashboard links={links}/>} 
 {page==='links'&&<section><div className="section-head"><h2>Meus Links</h2><button className="primary" onClick={()=>document.getElementById('title')?.focus()}><Plus size={18}/>Adicionar</button></div><form className="add" onSubmit={add}><input id="title" placeholder="Título" required value={newLink.title} onChange={e=>setNewLink({...newLink,title:e.target.value})}/><input placeholder="https://..." type="url" required value={newLink.url} onChange={e=>setNewLink({...newLink,url:e.target.value})}/><input placeholder="Descrição" value={newLink.description} onChange={e=>setNewLink({...newLink,description:e.target.value})}/><button className="primary"><Plus size={18}/>Salvar</button></form><div className="cards">{links.map(x=><article className="card" key={x.id}><div className="icon"><Link size={20}/></div><h3>{x.title}</h3><p>{x.description||'Sem descrição'}</p><a href={x.url} target="_blank" rel="noreferrer">{x.url}<ExternalLink size={14}/></a><div className="card-foot"><span>{x.clicks||0} cliques</span><button onClick={()=>navigator.clipboard.writeText(x.url)}><Copy size={15}/></button><button onClick={()=>del(x.id)}><Trash2 size={15}/></button></div></article>)}</div></section>}
 {page==='analytics'&&<section className="panel"><h2>Análises</h2><p>{links.reduce((a,x)=>a+(x.clicks||0),0)} cliques registrados.</p>{links.map(x=><div className="analytic-row" key={x.id}><span>{x.title}</span><b>{x.clicks||0}</b></div>)}</section>}
 {page==='profile'&&<section className="panel"><h2>{user.displayName}</h2><p>@{user.username}</p><p>{user.bio||'Adicione uma bio no seu perfil.'}</p><div className="profile-actions"><button className="secondary" onClick={()=>navigator.clipboard.writeText(publicUrl)}><Copy size={16}/>Copiar página pública</button><a className="secondary" href={`/u/${user.username}`} target="_blank" rel="noreferrer"><ExternalLink size={16}/>Abrir página</a></div></section>}
 {page==='settings'&&<section className="panel"><h2>Configurações</h2><p>Email: {user.email}</p><button className="danger" onClick={()=>{if(confirm('Sair da conta?'))logout()}}>Encerrar sessão</button></section>}
 </section></div>;
}
function Dashboard({links}:{links:Item[]}){const clicks=links.reduce((a,x)=>a+(x.clicks||0),0);return <section><div className="stats"><div><small>LINKS</small><strong>{links.length}</strong></div><div><small>CLIQUES</small><strong>{clicks}</strong></div><div><small>PLANO</small><strong>Básico</strong></div></div><div className="panel"><h2>Link mais acessado</h2>{links.length?<p>{[...links].sort((a,b)=>(b.clicks||0)-(a.clicks||0))[0].title}</p>:<p>Nenhum link cadastrado ainda.</p>}</div></section>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
